repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', '{extends: relaxed, rules: {line-length: {max: 120}}}']
        exclude: 'templates/.*\.yaml$|.*\.jinja$'

  - repo: local
    hooks:
      - id: helm-unittest
        name: helm unittest
        entry: bash -c 'cd charts/cert-chain && helm lint . && helm unittest .'
        language: system
        files: ^charts/cert-chain/.*$
        exclude: |
          (?x)^(
            charts/cert-chain/charts/.*|
            charts/cert-chain/Chart\.lock|
            charts/cert-chain/.*\.tgz
          )$
