---
# Enable local gateway logs and traces for all workloads.
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: default-access-logging
  namespace: istio-system
spec:
  accessLogging:
    - providers:
        - name: envoy
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
