nodeExporter:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    retention: 6h
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

serviceAccounts:
  alertmanager:
    create: false
  pushgateway:
    create: false
  server:
    create: true
